Adding some threading + queuing goodies to (hopefully) stop blocking things
plus a "flusher" that causes the queue to push to Loggly at intervals so
that stale records don't sit around during low traffic.

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -2,45 +2,46 @@
 
 set -e
 
-export PORT=${PORT:-9090}
-export INPUT_RECORD_COUNT=100
-export LOGGLY_TOKEN=fizzbuzz-$RANDOM
-export LOGGLY_SERVER="http://localhost:${PORT}"
-export LOGGLY_BATCH_SIZE=10
-export LOGGLY_MAX_LOOPS=10
+export PORT=${PORT:-19090}
+
 export EXE="${EXE:-./loggly_pipe/__main__.py}"
+export LOGGLY_BATCH_SIZE=10
+export LOGGLY_MAX_LINES=100
+export LOGGLY_SERVER="http://localhost:${PORT}"
+export LOGGLY_TOKEN=fizzbuzz-$RANDOM
+export LOOPS=200
 
 setup() {
-  ./loggly_pipe/fake_loggly_server.py >/dev/null 2>&1 &
+  ./loggly_pipe/fake_loggly_server.py >$1 2>$2 &
   export SERVER_PID="$!"
 
-  {
-    for i in $(seq 1 $INPUT_RECORD_COUNT) ; do
-      echo "{\"how_much_chuck\":\"$RANDOM\"}"
-    done
-  } > "$1"
+  while ! curl -s localhost:$PORT >/dev/null ; do
+    sleep 0.1
+  done
 }
 
 teardown() {
   kill "$SERVER_PID"
-  rm -f "${1:-$TMPIN}" "${2:-$TMPOUT}"
+  rm -f "${1:-$TMPOUT}" "${2:-$SERVEROUT}" "${3:-$SERVERERR}"
 }
 
 suite() {
   local exe="$1"
-  local input="$2"
-  local output="$3"
+  local output="$2"
+  local serveroutput="$3"
+  local servererr="$4"
   local exitstatus
 
   if [[ $DEBUG ]] ; then
     set -x
   fi
 
-  setup "$input"
+  setup "$serveroutput" "$servererr"
 
-  "$exe" < "$input" > "$output" 2>&1
+  echo "Running $exe > $output"
+  ./loggly_pipe/example_app.py | "$exe" > "$output"
 
-  if [[ $(grep -c '^{"_mark' "$output") == $LOGGLY_MAX_LOOPS ]] ; then
+  if [[ $(grep -c '^===> ' "$serveroutput") == $LOGGLY_MAX_LINES ]] ; then
     echo 'Success!'
     exitstatus=0
   else
@@ -49,16 +50,22 @@ suite() {
   fi
 
   if [[ $DEBUG ]] ; then
-    cat "$input" "$output"
+    echo '--- OUTPUT ---'
+    cat "$output"
+    echo '--- SERVER OUTPUT ---'
+    cat "$serveroutput"
+    echo '--- SERVER ERROR ---'
+    cat "$servererr"
   fi
 
-  teardown "$input" "$output"
+  teardown "$output" "$serveroutput" "$servererr"
   exit "$exitstatus"
 }
 
 trap 'teardown' SIGINT
 
-TMPIN=$(mktemp -t "loggly-pipe-$$.in.XXXX")
 TMPOUT=$(mktemp -t "loggly-pipe-$$.out.XXXX")
+SERVEROUT=$(mktemp -t "loggly-pipe-$$.server.out.XXXX")
+SERVERERR=$(mktemp -t "loggly-pipe-$$.server.err.XXXX")
 
-suite "$EXE" "$TMPIN" "$TMPOUT"
+suite "$EXE" "$TMPOUT" "$SERVEROUT" "$SERVERERR"
